benchmark_id: benchmark_ubix
fleet_id: 'fleet_ubix'
models: ["nemotron-nano-9b-v2"]
hyperparameters_space: 'space_1'
enable_logfire: false
runs: 1
experiments:
  zero_shot:
    experiment_type: zero_shot
    num_records: 1